// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: manager_desicion.sql

package db

import (
	"context"
	"database/sql"
)

const addDecision = `-- name: AddDecision :one
INSERT INTO "manager_decision" (
man_id,
decision,
message
)
VALUES ($1, $2, $3) RETURNING dec_id, man_id, decision, message
`

type AddDecisionParams struct {
	ManID    int64          `json:"man_id"`
	Decision bool           `json:"decision"`
	Message  sql.NullString `json:"message"`
}

func (q *Queries) AddDecision(ctx context.Context, arg AddDecisionParams) (ManagerDecision, error) {
	row := q.db.QueryRowContext(ctx, addDecision, arg.ManID, arg.Decision, arg.Message)
	var i ManagerDecision
	err := row.Scan(
		&i.DecID,
		&i.ManID,
		&i.Decision,
		&i.Message,
	)
	return i, err
}
