// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int64     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Manager struct {
	ID             int64  `json:"id"`
	FullName       string `json:"full_name"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
}

type ManagerDecision struct {
	DecID    int64          `json:"dec_id"`
	ManID    int64          `json:"man_id"`
	Decision bool           `json:"decision"`
	Message  sql.NullString `json:"message"`
}

type ReqQueue struct {
	ReqID int64           `json:"req_id"`
	Req   json.RawMessage `json:"req"`
}

type Transfer struct {
	ID            int64     `json:"id"`
	FromAccountID int64     `json:"from_account_id"`
	ToAccountID   int64     `json:"to_account_id"`
	Amount        int64     `json:"amount"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	Username          string       `json:"username"`
	HashedPassword    string       `json:"hashed_password"`
	FullName          string       `json:"full_name"`
	Email             string       `json:"email"`
	PasswordChangedAt time.Time    `json:"password_changed_at"`
	CreatedAt         sql.NullTime `json:"created_at"`
}
